openapi: 3.0.3
info:
  title: RingCentral Adaptive Cards Business Hours API
  description: RingCentral API specification
  version: 1.0.58-20240529-47eda8bd
  contact:
    name: RingCentral Developers Support
    url: https://developers.ringcentral.com/support
  termsOfService: https://www.ringcentral.com/legal/apilitos.html
  license:
    name: RingCentral API License Agreement
    url: https://www.ringcentral.com/legal/apilitos.html
servers:
- url: https://platform.ringcentral.com
  description: Production API entry point
- url: https://media.ringcentral.com
  description: Production Media entry point
- url: https://platform.devtest.ringcentral.com
  description: Developer sandbox API entry point
- url: https://platform.devtest.ringcentral.com
  description: Developer sandbox Media entry point
security:
- OAuth2: []
tags:
- name: Business Hours
paths:
  /restapi/v1.0/account/{accountId}/business-hours:
    get:
      tags:
      - Business Hours
      summary: Get Company Business Hours
      description: Returns the company business hours schedule. Business hours (and After hours - all the remaining time) schedules are commonly used for setting call handling rules - `business-hours-rule` and `after-hours-rule` correspondingly.
      operationId: readCompanyBusinessHours
      parameters:
      - $ref: '#/components/parameters/AccountId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyBusinessHours'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '503':
          $ref: '#/components/responses/ServiceNotAvailable'
      x-feature: ReadExtensionAnsweringRules
      x-availability: High
      x-throttling-group: Light
      x-app-permission: ReadAccounts
      x-user-permission: ReadCompanyAnsweringRules
    put:
      tags:
      - Business Hours
      summary: Update Company Business Hours
      description: Updates the company business hours schedule.
      operationId: updateCompanyBusinessHours
      parameters:
      - $ref: '#/components/parameters/AccountId'
      requestBody:
        description: JSON body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyBusinessHoursUpdateRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyBusinessHours'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '503':
          $ref: '#/components/responses/ServiceNotAvailable'
      x-feature: EditExtensionAnsweringRules
      x-availability: Limited
      x-throttling-group: Medium
      x-app-permission: EditExtensions
      x-user-permission: EditUserAnsweringRules
  /restapi/v1.0/account/{accountId}/extension/{extensionId}/business-hours:
    get:
      tags:
      - Business Hours
      summary: Get User Business Hours
      description: Returns the user business hours schedule. Business hours (and After hours - all the remaining time) schedules are commonly used for setting call handling rules - `business-hours-rule` and `after-hours-rule` correspondingly. **Please note:** If the user business hours are set to 'Custom hours' then a particular schedule is returned; however if set to '24 hours/7 days a week' the schedule will be empty.
      operationId: readUserBusinessHours
      parameters:
      - $ref: '#/components/parameters/AccountId'
      - $ref: '#/components/parameters/ExtensionId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserBusinessHoursResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '503':
          $ref: '#/components/responses/ServiceNotAvailable'
      x-feature: ReadExtensions
      x-availability: High
      x-throttling-group: Light
      x-app-permission: ReadAccounts
      x-user-permission: ReadExtensions
    put:
      tags:
      - Business Hours
      summary: Update User Business Hours
      description: Updates the user business hours schedule.
      operationId: updateUserBusinessHours
      parameters:
      - $ref: '#/components/parameters/AccountId'
      - $ref: '#/components/parameters/ExtensionId'
      requestBody:
        description: JSON body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserBusinessHoursUpdateRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserBusinessHoursUpdateResponse'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '503':
          $ref: '#/components/responses/ServiceNotAvailable'
      x-feature: EditExtensionAnsweringRules
      x-availability: Limited
      x-throttling-group: Medium
      x-app-permission: EditExtensions
      x-user-permission: EditUserAnsweringRules
components:
  schemas:
    CompanyBusinessHoursScheduleInfo:
      type: object
      properties:
        weeklyRanges:
          $ref: '#/components/schemas/WeeklyScheduleInfo'
      description: Schedule when an answering rule is applied
    ApiErrorWithParameter:
      description: 'The error model with additional attributes which can be used for HTTP 400/409

        This is a deprecated model: "ApiError" model can be used instead with arbitrary additional parameters

        '
      allOf:
      - $ref: '#/components/schemas/ApiError'
      - type: object
        properties:
          parameterName:
            type: string
            description: The name of the API parameter/attribute which caused the error
          parameterValue:
            type: string
            description: The value of the API parameter/attribute which caused the error
    ApiError:
      type: object
      description: Generalized API error structure suitable for any error type
      required:
      - errorCode
      - message
      properties:
        errorCode:
          type: string
          description: Logical error code (typically, 3 letters followed with number, dash separated)
          example: XXX-123
        message:
          type: string
          description: User-friendly error message
          example: Something went wrong
      additionalProperties: true
    CompanyBusinessHours:
      type: object
      properties:
        uri:
          type: string
          format: uri
          description: 'Canonical URI of a business-hours resource '
        schedule:
          $ref: '#/components/schemas/CompanyBusinessHoursScheduleInfo'
      example:
        uri: https://platform.ringcentral.com/restapi/v1.0/account/401800045008/business-hours
        schedule:
          weeklyRanges:
            wednesday:
            - from: 09:00
              to: '18:00'
            friday:
            - from: 09:00
              to: '18:00'
            tuesday:
            - from: 09:00
              to: '18:00'
            monday:
            - from: 09:00
              to: '18:00'
            thursday:
            - from: 09:00
              to: '18:00'
    ApiErrorResponseModel:
      type: object
      description: Standard error response model which is returned in case of any unsuccessful operation
      required:
      - errors
      properties:
        errors:
          type: array
          description: The array of errors (there will be just one in the most of the cases)
          minItems: 1
          items:
            $ref: '#/components/schemas/ApiError'
    WeeklyScheduleInfo:
      type: object
      properties:
        monday:
          type: array
          description: Time intervals for a particular day
          items:
            $ref: '#/components/schemas/TimeInterval'
        tuesday:
          type: array
          description: Time intervals for a particular day
          items:
            $ref: '#/components/schemas/TimeInterval'
        wednesday:
          type: array
          description: Time intervals for a particular day
          items:
            $ref: '#/components/schemas/TimeInterval'
        thursday:
          type: array
          description: Time intervals for a particular day
          items:
            $ref: '#/components/schemas/TimeInterval'
        friday:
          type: array
          description: Time intervals for a particular day
          items:
            $ref: '#/components/schemas/TimeInterval'
        saturday:
          type: array
          description: Time intervals for a particular day
          items:
            $ref: '#/components/schemas/TimeInterval'
        sunday:
          type: array
          description: Time intervals for a particular day
          items:
            $ref: '#/components/schemas/TimeInterval'
      description: Weekly schedule
    ScheduleInfoUserBusinessHours:
      type: object
      properties:
        weeklyRanges:
          $ref: '#/components/schemas/WeeklyScheduleInfo'
      description: Schedule when an answering rule is applied
    UserBusinessHoursScheduleInfo:
      type: object
      properties:
        weeklyRanges:
          $ref: '#/components/schemas/WeeklyScheduleInfo'
      description: Schedule when an answering rule is applied
    CompanyBusinessHoursUpdateRequest:
      type: object
      properties:
        schedule:
          $ref: '#/components/schemas/CompanyBusinessHoursScheduleInfo'
      example:
        schedule:
          weeklyRanges:
            tuesday:
            - from: 09:00
              to: '18:00'
            friday:
            - from: 09:00
              to: '18:00'
            thursday:
            - from: 09:00
              to: '18:00'
            wednesday:
            - from: 09:00
              to: '18:00'
            monday:
            - from: 09:00
              to: '18:00'
    GetUserBusinessHoursResponse:
      type: object
      properties:
        uri:
          type: string
          format: uri
          description: Canonical URI of a business-hours resource
        schedule:
          $ref: '#/components/schemas/ScheduleInfoUserBusinessHours'
      example:
        uri: https://restapi/v1.0/account/401800045008/extension/401800045008/business-hours
        schedule:
          weeklyRanges:
            wednesday:
            - from: 09:00
              to: '18:00'
            friday:
            - from: 09:00
              to: '18:00'
            tuesday:
            - from: 09:00
              to: '18:00'
            monday:
            - from: 09:00
              to: '18:00'
            thursday:
            - from: 09:00
              to: '18:00'
    TimeInterval:
      type: object
      properties:
        from:
          type: string
          description: Time in format hh:mm
        to:
          type: string
          description: Time in format hh:mm
    ParameterizedErrorResponseModel:
      type: object
      description: Standard error response which may include parameterized errors
      required:
      - errors
      properties:
        errors:
          type: array
          description: The array of errors (there will be just one in the most of the cases)
          minItems: 1
          items:
            $ref: '#/components/schemas/ApiErrorWithParameter'
    UserBusinessHoursUpdateResponse:
      type: object
      properties:
        uri:
          type: string
          format: uri
          description: Canonical URI of a business-hours resource
        schedule:
          $ref: '#/components/schemas/UserBusinessHoursScheduleInfo'
    UserBusinessHoursUpdateRequest:
      required:
      - schedule
      type: object
      properties:
        schedule:
          $ref: '#/components/schemas/UserBusinessHoursScheduleInfo'
  responses:
    NotFound:
      description: 'General response with **HTTP 404 "Not found"** status.<br>

        Reasons: the entity with given ID (typically specified in a path parameter), is not found or inaccessible

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponseModel'
    ServiceNotAvailable:
      description: 'General response with **HTTP 503 "Service not available"** status.<br>

        Reasons: server cannot process the request because of being overloaded, misconfiguration or other issues.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponseModel'
    InternalError:
      description: 'General response with **HTTP 500 "Internal Server Error"** status.<br>

        Reasons: general server-side error.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponseModel'
    InvalidRequest:
      description: 'General response with **HTTP 400 "Bad request"** status.<br>

        Reasons: unparsable request, path, query or body parameters are invalid.

        The error description may contain reference to particular parameter(s) which haven''t passed the validation.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ParameterizedErrorResponseModel'
  parameters:
    AccountId:
      name: accountId
      in: path
      description: 'Internal identifier of the RingCentral account

        (can be set to "~" to indicate that the account associated with current authorization session should be used)

        '
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: '~'
      example: '~'
    ExtensionId:
      name: extensionId
      in: path
      description: 'Internal identifier of the RingCentral extension/user

        (can be set to "~" to indicate that the extension associated with current authorization session should be used)

        '
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: '~'
      example: '~'
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://platform.ringcentral.com/restapi/oauth/authorize
          tokenUrl: https://platform.ringcentral.com/restapi/oauth/token
          refreshUrl: https://platform.ringcentral.com/restapi/oauth/token
          scopes: {}
x-tagGroups:
- name: Voice
  popular: true
  tags:
  - Business Hours
  - Call Blocking
  - Call Control
  - Call Forwarding
  - Call Handling Rules
  - Interaction Rules
  - State-based Rules
  - Call Flip
  - Call Log
  - Call History
  - Call Log Export
  - Call Monitoring Groups
  - Call Queues
  - Call Recordings
  - Call Recording Settings
  - Device SIP Registration
  - Greetings
  - IVR
  - RingOut
  - Verification Calls
- name: SMS and Fax
  popular: true
  tags:
  - Fax
  - Message Exports
  - Message Store
  - Pager Messages
  - SMS
  - High Volume SMS
  - SMS Log Export
  - SMS Templates
  - Voicemail Broadcasting
- name: Social Messaging
  popular: true
  tags:
  - Identities
  - Contents
- name: Team Messaging
  popular: true
  tags:
  - Adaptive Cards
  - Bots
  - Calendar Events
  - Chats
  - Conversations
  - Compliance Exports
  - Contacts
  - Incoming Webhooks
  - Notes
  - Posts
  - Profile
  - Tasks
  - Teams
- name: Video
  popular: true
  tags:
  - Bridge Management
  - Delegation Management
  - Meetings History
  - Meeting Recordings
  - RCM Meetings (Legacy)
  - RCM Webinars (Legacy)
- name: Webinar
  popular: true
  tags:
  - Webinars and Sessions
  - Invitees
  - Historical Webinars
  - Historical Recordings
  - Registration Management
  - Registrants
  - Webinar Analytics
  - Webinar Subscriptions
- name: Analytics
  popular: true
  tags:
  - Business Analytics
- name: Artificial Intelligence
  popular: true
  tags:
  - Insights
  - Audio
  - Text
  - Status
- name: Authentication
  tags:
  - OAuth 2.0 / OpenID Connect
  - Interoperability
- name: Account
  tags:
  - Company
  - Custom Fields
  - Features
  - Licenses
  - Tax Locations
  - Cost Centers
  - Multi-Site
  - Phone Numbers
  - Presence
  - Regional Settings
  - User Permissions
  - User Settings
  - Audit Trail
  - Calling Rates
  - Appearance Customization
  - Account Integrations
- name: Provisioning
  tags:
  - Automatic Location Updates
  - Devices
  - Extensions
  - Paging Only Groups
  - Park Locations
  - Phone Lines
  - SCIM
  - Shared Lines
  - Group Call Pickup
  - Delegated Lines Groups
  - Directed Call Pickup
  - IVR Apps
  - Video Configuration
  - Number Porting
  - SMB
  - Account Federation
  - Integrations
  - Enterprise Portal API
  - Push to Talk Provisioning
  - BYOC
- name: Address Book
  tags:
  - External Contacts
  - Internal Contacts
  - Hybrid Directory Contacts
  - Overlay Contacts
  - External Shared Directory
- name: Roles and Permissions
  tags:
  - Permissions
  - Role Management
  - Site Administration
  - User Groups
- name: Events & Notifications
  tags:
  - Subscriptions
- name: User Integrations
  tags:
  - Token Management
  - Calendar Management
  - Calendar Event Management
  - Calendar Presence Link
  - Cloud Personal Contacts
  - Cloud Shared Contacts
  - Cloud Directory
  - Deprecated Calendar API
- name: Rooms
  tags:
  - Rooms Client API
  - Rooms Management API
- name: App Management
  tags:
  - App Gallery
  - App Rating Review
  - Bot Provisioning
- name: Workflow Builder
  tags:
  - Flows
  - Flow Editor
  - Flow Log
  - Flow Templates
- name: Utilities
  tags:
  - API Info
  - Application Settings
  - Async Tasks
  - User Notifications
  - Client Versions
  - End-to-End Encryption
